version: '3'
services: 
    db:
        image:  'mongo:latest'
        container_name: 'mongodb-server'
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dHuh8h28h74JHGHYV672BY6h
            MONGO_INITDB_DATABASE: fajruldb
        command: mongod
        volumes: 
            - ./init-db:/docker-entrypoint-initdb.d/
        ports:
            - '27017:27017'
        restart: always

    app:
        image: "mongo-express:latest" 
        container_name: 'mongodb-manager'
        restart: always
        depends_on:
            - db
        environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=root
         - ME_CONFIG_MONGODB_ADMINPASSWORD=dHuh8h28h74JHGHYV672BY6h
         - ME_CONFIG_MONGODB_SERVER=db
         - ME_CONFIG_BASICAUTH_USERNAME=user
         - ME_CONFIG_BASICAUTH_PASSWORD=user
        ports:
         - '8081:8081'